# compose.override.yml
version: "3.9"

#########################
# 1) On remappe les volumes
#########################
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/SnapServer/db"

  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/SnapServer/storage"

  ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/SnapServer/ssl"
