version: "3.9"

#############################################
# 1) On remplace les volumes nommés par des bind-mounts
#############################################
volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/snapcamera/storage"

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/snapcamera/db"

#############################################
# 2) On redéfinit les deux montages SSL du service webproxy
#############################################
services:
  webproxy:
    volumes:
      - "/mnt/TrueNas Server/Stockage_TrueNas/snapcamera/ssl/studio-app.snapchat.com.crt:/etc/ssl/certs/studio-app.snapchat.com.crt:ro"
      - "/mnt/TrueNas Server/Stockage_TrueNas/snapcamera/ssl/studio-app.snapchat.com.key:/etc/ssl/private/studio-app.snapchat.com.key:ro"
