version: "3.9"

volumes:
  mysql-db:                               # ← nom exact du volume dans le compose d’origine
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/SnapServer/db"

  server-storage:                         # volume « storage » du compose (name: server-storage)
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/SnapServer/storage"

  ssl:                                    # volume « ssl » du compose (name: ssl)
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/TrueNas Server/Stockage_TrueNas/SnapServer/ssl"
