blank_issues_enabled: false
contact_links:
  - name: List of incompatible Lenses
    url: https://github.com/ptrumpis/snap-camera-server/discussions/8
    about: Report non working lenses here.
  - name: Q&A
    url: https://github.com/ptrumpis/snap-camera-server/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Share ideas for new features
    url: https://github.com/ptrumpis/snap-camera-server/discussions/categories/ideas
    about: You can ask for feature requests here